export {default as Authentication} from './Authentication.vue'
export {default as Donation} from './Donation.vue'
export {default as Home} from './Home.vue'
export {default as Support} from './Suport.vue'
export {default as Profile} from './Profile.vue'