name: CI + Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # importante para versionamento

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run lint
      - run: npm run build

      - name: Gerar release automático
        run: npm run release

      - name: Push das mudanças
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push --follow-tags